# Generated by Django 6.0.3 on 2026-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_sugar',
            field=models.BooleanField(default=False),
        ),
    ]
