# Generated by Django 6.0.3 on 2026-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_groupinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvite',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('editor', 'Editor'), ('view_only', 'View Only')], default='view_only', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('editor', 'Editor'), ('view_only', 'View Only')], default='view_only', max_length=20),
        ),
    ]
